### ISSUE TITLE
Use with PowerShell and WPF Apps XAML

### ISSUE THREAD

**Issue by JM2K69** [Keboo/ShowMeTheXAML#5]
I create some WPF application  with powershell and XAML I want to know if I can use ShowMeTheXAML.

Thank you.

**Comment by Keboo** [comment]
@JM2K69 yes you should be able to. There is nothing in this library that should get in the way. In your intent to display XAML inside of your app?

**Comment by JM2K69** [comment]
Ok thank you but how to do this in powershell 
protected override void OnStartup(StartupEventArgs e)
{
    XamlDisplay.Init();
    base.OnStartup(e);
}

**Comment by Keboo** [comment]
@JM2K69 you just need to make sure you invoke the `XamlDisplay.Init()` method is invoked before you use it. So you could do it right at the beginning of your Window's constructor.

**Comment by JM2K69** [comment]
I how to find the constructor name ?

**Comment by JM2K69** [comment]
I found It [ShowMeTheXAML.XamlDisplay]::Init()

**Comment by JM2K69** [comment]
When I launch I have one error 

Exception lors de l'appel de «Init» avec «0» argument(s): «La référence d'objet n'est pas définie à une instance d'un objet.»
Au caractère H:\Mahapps\AES - Copie\Password.ps1:288 : 1
+ [ShowMeTheXAML.XamlDisplay]::Init()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NullReferenceException

**Comment by Keboo** [comment]
I just pushed out a new NuGet 1.0.11 that should fix the null reference exception. I suspect the issue was the entry assembly being null because it is being loaded from powershell. 

Are you sure you need this library for your project? This library's purpose is intended to be used to display XAML to make it easy for people to learn what XAML they need to use in their own projects. Is this functionality what you need?

**Comment by Keboo** [comment]
I believe the latest versions have addressed this bug, if there are still issues let me know

**Comment by JM2K69** [comment]
hey Keboo, I have an error when I try to Add the nuget packages ShowMeTheXAML.AvalonEdit
I Use the [ShowMeTheXAML.XamlDisplay]::Init() but nothing appear If I remove the ShowMeTheXAML.AvalonEdit for the new style I have nothing Here my project [Link](https://1drv.ms/f/s!AqCYCKrMXFdkg95gti1YrfUW75mgvw)

 ```Exception lors de l'appel de « Load » avec « 1 » argument(s) : « La propriété Set 'System.Windows.ResourceDictionary.DeferrableContent' a levé une exception. » ```

**Comment by JM2K69** [comment]
Here the sample
[Application.zip](https://github.com/Keboo/ShowMeTheXAML/files/3455586/Application.zip)

**Comment by Keboo** [comment]
@JM2K69 so there are a few changes you need to make to that script.

1. ShowMeTheXaml.AvalonEdit requires that you load in the [AvalonEdit](http://avalonedit.net/) dll. This is the ICSharpCode.AvalonEdit.dll. You can get it from the [NuGet](https://www.nuget.org/packages/AvalonEdit)
2. You probably want to reference the default style dictionary in your xaml. So `<ResourceDictionary Source="pack://application:,,,/ShowMeTheXAML.AvalonEdit;component/Themes/default.xaml" />` This will set the default style for the `XamlDisplay` control.
3. Because this code is not compiled, this library has pretty limited value in powershell. Because it can't really use the MSBuild task it wont be able to automatically generate the setup lines needed for the `XamlDisplay` control needs. You can however manually put in this information. Something like this:
```ps
[ShowMeTheXAML.XamlResolver]::Set("SomeUniqueString", "<Xaml Here=""Value"">Child</Xaml>")
```
